config/routes.rb
Rails.application.routes.draw do
  resources :shippings
  resources :orders
  resources :addresses
  resources :customers
  resources :products
  resources :delivery

  resources :bulk_delivery do
    collection { post :import }
  end

  root 'bulk_delivery#index'

end

app/models/shipping.rb
class Shipping
  include Mongoid::Document
  field :company, type: String
  field :tracking_number, type: String
  field :status, type: String

  belongs_to :order, class_name: "Order", inverse_of: :order
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
  before_action :set_shipping, only: [:show, :edit, :update, :destroy]

  # GET /shippings
  # GET /shippings.json
  def index
    @shippings = Shipping.all
  end

  # GET /shippings/1
  # GET /shippings/1.json
  def show
  end

  # GET /shippings/new
  def new
    @shipping = Shipping.new
  end

  # GET /shippings/1/edit
  def edit
  end

  # POST /shippings
  # POST /shippings.json
  def create
    @shipping = Shipping.new(shipping_params)

    respond_to do |format|
      if @shipping.save
        format.html { redirect_to @shipping, notice: 'Shipping was successfully created.' }
        format.json { render :show, status: :created, location: @shipping }
      else
        format.html { render :new }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shippings/1
  # PATCH/PUT /shippings/1.json
  def update
    respond_to do |format|
      if @shipping.update(shipping_params)
        format.html { redirect_to @shipping, notice: 'Shipping was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipping }
      else
        format.html { render :edit }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippings/1
  # DELETE /shippings/1.json
  def destroy
    @shipping.destroy
    respond_to do |format|
      format.html { redirect_to shippings_url, notice: 'Shipping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping
      @shipping = Shipping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_params
      params.require(:shipping).permit(:company, :tracking_number, :status)
    end
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/shippings/_form.html.erb
<%= form_for(@shipping) do |f| %>
  <% if @shipping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipping.errors.count, "error") %> prohibited this shipping from being saved:</h2>

      <ul>
      <% @shipping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :tracking_number %><br>
    <%= f.text_field :tracking_number %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shippings/edit.html.erb
<h1>Editing Shipping</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping %> |
<%= link_to 'Back', shippings_path %>

app/views/shippings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shippings</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Tracking number</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shippings.each do |shipping| %>
      <tr>
        <td><%= shipping.company %></td>
        <td><%= shipping.tracking_number %></td>
        <td><%= shipping.status %></td>
        <td><%= link_to 'Show', shipping %></td>
        <td><%= link_to 'Edit', edit_shipping_path(shipping) %></td>
        <td><%= link_to 'Destroy', shipping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping', new_shipping_path %>

app/views/shippings/new.html.erb
<h1>New Shipping</h1>

<%= render 'form' %>

<%= link_to 'Back', shippings_path %>

app/views/shippings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @shipping.company %>
</p>

<p>
  <strong>Tracking number:</strong>
  <%= @shipping.tracking_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @shipping.status %>
</p>

<%= link_to 'Edit', edit_shipping_path(@shipping) %> |
<%= link_to 'Back', shippings_path %>